### PR TITLE
Added d3d9 render

### PR DESCRIPTION
**Pull request by iHimiko**
Added d3d9 render

### CODE REVIEW

**Comment by iHimiko** [comment]
Sorry, caching doesn't work, I'm fixing

**Comment by Gl0** [comment]
doing the same now )

**Comment by Gl0** [comment]
Got it working (refactored a bit), but seems we need another implementation of dx9_overlay.dll
Current one doesn't support any characters other than 32-127 ASCII, we need something with full unicode support, and better using ingame font from specified file to be sure that all characters that can be displayed ingame can also be displayed in overlay.
Another problem - issues with game restart while meter is running. Managed to show overlay back in ~70% cases, but seems it's not good enough, need some better workaround.

**Comment by iHimiko** [comment]
Well, I'll try to do a build with Unicode support and fix problem with z-index of text and boxes. Thanks for response

**Comment by Gl0** [comment]
My code don't have problems with z-index (reuse all labels without disposing and use only one box).
but need another implementation of https://github.com/agrippa1994/DX9-Overlay-API/blob/master/src/dx9_overlay/Game/Rendering/D3DFont.cpp#L175

**Comment by Gl0** [comment]
published my changes to https://github.com/neowutran/ShinraMeter/tree/overlay
if we find the way to use non-ascii symbols - will merge it to master

**Comment by iHimiko** [comment]
Thanks so much

**Comment by iHimiko** [comment]
good luck

**Pull request closed without merging**
